### ISSUE TITLE
epub version

### ISSUE THREAD

**Issue by squiddle** [berb/diploma-thesis#3]
i would love to have an epub version. I tried with [pandoc](http://johnmacfarlane.net/pandoc/) but i don't know how to use this to create a correct toc from the html input.

```
pandoc -f html -t epub -o berb.epub original/*.html
```

**Comment by berb** [comment]
Have you tried to exclude the index.html and use the `--toc` parameter from pandoc instead?

Addendum: Perhaps also `-s`

**Comment by squiddle** [comment]
I tried, same results. It only creates a toc entry for an empty title page and another toc entry with the complete document. I will try to find some time to investigate. But first i will read the pdf.

**Comment by berb** [comment]
I tried for myself and the TOC has been created correctly. The problem right now is that internal links are lost and the link targets on the bibliography page are removed automatically.

**Comment by berb** [comment]
There is now a preliminary epub version (cb2ca51).
