### ISSUE TITLE
Awkward sentence

### ISSUE THREAD

**Issue by ggerard** [berb/diploma-thesis#8]
http://berb.github.com/diploma-thesis/community/052_threads.html

Awkward:
The synchronized keyword allows to guard an entire method or a distinct code block, using the callee resp. a given object as monitor object.

Suggest:
The synchronized keyword guards an entire method or a distinct code block using a given object as monitor.

I'm not sure the suggestion matches the original intent but the grammar is cleaned up and more succinct. I have no idea what "using the callee resp. a given..." means.

**Comment by berb** [comment]
Thanks, I'll have a look and fix this.
